swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
schemes:
  - https
paths:
  /Produits:
    get:
      summary: retourne la liste des produits.
      produces:
        - application/json
      responses:
        200:
          description: OK
  /Produits/{id}:
    get:
      summary: retourne le produit correspondant à l'id
      parameters:
        - name: id
          type: number
          in: path
          description: id du produit
          required: true
      produces:
        - application/json
      responses:
        200:
          description: ok
  /Produits/create:
    post:
      summary: créer un produit
      parameters:
        - name: produit
          type: number
          in: query
          description: produit à ajouté
          required: true
      produces:
        - application/json
      responses:
        200:
          description: le produit créer

  /Produits/delete/{id}:
    post:
      summary: supprime un produit correspondant à l'id
      parameters:
        - name: id
          type: number
          in: path
          description: id du produit à supprimé
          required: true
      responses:
        200:
          description: le produit a été supprimé

definitions:
    Produit:
      type: object
      required:
        - id
        - nom
      properties:
        id:
          type: number
        nom:
          type: string

